### ISSUE TITLE
Request for adding Lazarus/Free Pascal

### ISSUE THREAD

**Issue by Mai-Lapyst** [exercism/request-new-language-track#116]
**What programming language should we add?**
Free Pascal/Lazarus

**What is the official website for the language?**
Lazarus: https://www.lazarus-ide.org/
Free Pascal (or FPC for short): https://www.freepascal.org/

**Is this a language that comes in many variants? If so, which variant should we support?**
This Language is already a Variant of an Language: Object Pascal. Another Variant would be Delphi Pascal, which is already be added to Exercism.

**Does the language have an official/unofficial logo?**
This is a bit tricky, because Lazarus and FPC themself are at the base level distinct Projects.
But Lazarus and FPC are made from the same People, but Lazarus's Logo might be more recognizeable.
(Because Lazarus is the IDE and most people will know the IDE more rather than its compiler FPC).

Lazarus IDE: https://wiki.freepascal.org/File:Lazarus-icons-lpr-proposal-bpsoftware.png
Sometimes also uses this logo (for example on their Website): https://wiki.freepascal.org/File:Lazarus-icons-exe-proposal-bpsoftware.png

Free Pascal actually uses an GIF as their logo: https://wiki.freepascal.org/File:fpc_running_logo.gif

All Logos can be found here: https://wiki.freepascal.org/Logos_and_Banners
Currently the wiki dosnt state explicitly how the Logos mentioned above are licensed.
In general FPC is licensed under a combination of MDL ,LGPL and GPLv2: https://wiki.freepascal.org/licensing .
So it would be natural that the offical logos would also fall under this License. There also exists an forum thread about this,
in which the conclusion was:
```
[...] that page (https://wiki.freepascal.org/Logos_and_Banners) would have no sense if we were not allowed to use those.
```
Source: https://forum.lazarus.freepascal.org/index.php/topic,22315.msg131457.html#msg131457

**Is there a testing framework available for the language?**

Yes: https://wiki.freepascal.org/fpcunit

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?**

No, not really. Highlightjs only officially supports Delphi.

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**

Highlightjs only officially supports Delphi. But since the both languages are syntactical Identical, this should be no problem.

- what is Highlightjs' canonical spelling for the language? "Delphi"
- what file extensions should be highlighted? ".pas"-Files

**Who will be leading the effort to launch the track?**

I'm new on contributing to exercism but I could maintain the track. (If this is what the question was intended to ask for)
Otherwise it might be good to cooperate with the people that lead the already existing delphi track at https://github.com/exercism/delphi

**Comment by iHiD** [comment]
@Mai-Lapyst Thanks for this. How different are Lazarus and Delphi? e.g. Would the exercises need changing significantly?

**Comment by Mai-Lapyst** [comment]
@iHiD Thanks for responding so quickly!

The main differences between Delphi and FPC/Lazarus are:

- FPC dosn't support Generics
- Exporting of overloaded functions in librarys are not possible
- Delegating interfaces to classes is not always supported
- Anonymous Methods are not supported
- Custom attributes are not supported
- Enhanced RTTI is not supported (compiler directives)
- Imports via "uses" keyword sometimes are named differently.
  For example: Delphi allows "System.SysUtils" and "SysUtils" while FPC only has "SysUtils".
- Various compiler directives are missing in one or the other.
- {$include} works differently: FPC also supports accessing compiler information or environment variables through this compiler directive

This are the most common found differences. There might be more, and I can research this further if theres need for it.

As for the exercises: It depends what the exercises are using/teaching. For example an exercise with generics wouldn't work with FPC/Lazarus until they implement generics.

The Tests also might need some changes, but this depends on weather or not fpcunit and DUnitX (the test framework used in the delphi track) share the same API. If not, there needs to be further testing if DUnitX works with FPC/Lazarus, but since FPC lacks some features of Delphi (generics, anonymous methods) this might be not the case.

**Comment by iHiD** [comment]
Feels like we could do this. @ErikSchierboom Could you have a read of the above and see if you agree pls? If so, would it make sense to fork the @exercism/delphi repo for this, or go from scratch?

**Comment by ErikSchierboom** [comment]
We've discussed this for a bit, and here are our thoughts.

AFAIC, Lazarus/Free Pascal is _very_ similar in Delphi, lacking only some language features. Delphi itself must be coded in an IDE that only runs on Windows. This is not ideal for students, as there will be students working on other OS'es that can't or don't want to run Windows natively or in a VM. Those students will be missing out on Delphi.

That said, creating a separate track which language is mostly identical to another track also seems sub-optimal, as people would be learning (virtually) the same language via two different tracks. It would also mean that mentors would have to be spread over two tracks, as well as any coding efforts like implementing exercises or track tooling being duplicated.

What if, instead of creating a new track, we'd update the Delphi track to offer Lazarus/Free Pascal as an alternative for students that don't want to work on Windows? We could create a new document in the Delphi repo listing the differences between the languages and have a separate section in the `INSTALLATION.md` document on how to setup Lazarus/Free Pascal as an alternative IDE.

@rpottsoh We're also very keen on hearing your thoughts.

**Comment by rpottsoh** [comment]
Lazarus/FPC is another dialect of Pascal, like Delphi.  I think a single language track would have a hard time trying to be compatible with both dialects.  There are just too many differences to contend with.

Development is in progress to make it possible for learners to submit exercises directly from the online editor available on the Exercism site in order to see how their solution fairs against the tests provided.

If a learner chooses to work this way then they do not need to install anything.  I admit I do not entirely know how this new capability operates in V3 of Exercism; I am assuming one could work offline in their editor of choice and submit their solution using the CLI, or copy & paste to the online editor to then see the results.

Besides all of the nuanced differences between the two Pascal dialects, the test framework I have implemented for the Delphi track (DUnitX) heavily relies on the features available to Delphi that are not available to Lazarus/FPC.  DUnitX is well maintained by its author and has fairly regular updates.

To support both compilers, at the very least, a test framework that is known to work with both compilers would have to be used.   All of the exercises in the Delphi track would need to be rewritten to support another testing framework.  DUnit I think is a framework that is compatible with both compilers (unconfirmed).  DUnit is provided with Delphi and is available to Lazarus/FPC.

Supporting Lazarus/FPC is more work than I am willing to take on.

**Comment by ErikSchierboom** [comment]
Thanks for the detailed explanation. It sounds like we probably _do_ want separate tracks then.

**Comment by ErikSchierboom** [comment]
@Mai-Lapyst Are you still interested in working on a Lazarus/Free Pascal track?

**Comment by kytrinyx** [comment]
We need to decide on the name and ID for the track. Are we good with `Lazarus/Free Pascal` and `lazarus-free-pascal` or is there something a bit shorter that would be suitable?

**Comment by ErikSchierboom** [comment]
If I'm reading it correctly, Lazarus is the IDE and Free Pascal the language. Is that correct @Mai-Lapyst? If so, the name should be `free-pascal` I think.

**Comment by kytrinyx** [comment]
I'm going to go ahead and generate the repo, and if we got it wrong, just holler and we can delete it and redo it.

**Comment by kytrinyx** [comment]
I've created the repo here: https://github.com/exercism/free-pascal/issues/1

@Mai-Lapyst you should have an invitation to the maintainer team for the new track.
