### ISSUE TITLE
Request for Dart track (Repository with tests and exercises already created)

### ISSUE THREAD

**Issue by SuperPaintman** [exercism/request-new-language-track#32]
Hi, @kytrinyx !

**What programming language should we add?**
[Dart lang](https://www.dartlang.org/)

**What is the official website for the language?**
<https://www.dartlang.org/>

**Is this a language that comes in many variants? If so, which variant should we support?**
no

**Is there a testing framework available for the language?**
yes, <https://www.dartlang.org/guides/testing>

**Who will be leading the effort to launch the track?**
Someone from the [community](https://www.dartlang.org/community). Or maybe me?

I also create a repository (with exercises, auto-testing, documentation, guidelines and etc):

<https://github.com/SuperPaintman/exercism-dart>

And the logo:

![](https://raw.githubusercontent.com/SuperPaintman/exercism-dart/master/img/icon.png)

**Comment by kytrinyx** [comment]
Hi there @SuperPaintman, this is great stuff.

I'm going to bootstrap a repository for you within this organization, though I see that you created a repo yourself. This will give us the benefit of all the existing boilerplate.

- [ ] Run bootstrap script
  `TRACK_ID=<id> LANGUAGE=<language> bin/bootstrap`
- [ ] Turn on [Travis CI][travis]
- [ ] If Windows-specific language, turn on [AppVeyor][appveyor]
- [ ] If Mac-specific language, turn on [Circle CI][circle]
  Add it as a Linux project, then switch it to OS X in _Project Settings -> Build Environment_
- [ ] Add as a submodule to [trackler][]
  `TRACK_ID=<id>; git submodule add https://github.com/exercism/x$TRACK_ID tracks/$TRACK_ID`
- [ ] Add the requestor(s) to the exercism/track-maintainers team
- [ ] Create a [new team][new-team] for language
- [ ] Add the bootstrapped repository to the team **with write access**
- [ ] Invite requestor(s) to the new team
- [ ] Make a note of the new track and maintainers for the newsletter

[travis]: https://travis-ci.org/profile/exercism
[appveyor]: https://ci.appveyor.com/projects/new
[circle]: https://circleci.com/gh/organizations/exercism/settings#projects
[trackler]: https://github.com/exercism/trackler/tree/master/tracks
[new-team]: https://github.com/orgs/exercism/new-team

**Comment by SuperPaintman** [comment]
Glad to hear it! Something is required of me?

**Comment by kytrinyx** [comment]
I'm working my way through the checklist, once I've got that I'll have something for you 🌻

**Comment by kytrinyx** [comment]
Alrighty, the repo is ready for you.

The launch checklist is here:

https://github.com/exercism/dartlang/issues/1

Please submit individual pull requests with cohesive changes (e.g. documentation, CI setup, logo, individual exercises) to the new repo. I've given you commit access, so you can create branches right in the repo rather than creating a fork. Individual, smaller PRs will give us a few benefits:

* I can help catch things that should have been documented but weren't
* Ongoing development will be visible/transparent to others who are interested in following along
* It will be easier to go back in the git logs to figure things out

If you find things that are odd or confusing, holler.  You can find other track maintainers in the chat room at https://gitter.im/exercism/dev (probably other rooms, too).

Welcome :heart: :heart: :heart:

**Comment by SuperPaintman** [comment]
Cool! Thank you, Katrina
