### ISSUE TITLE
Language request: Nix

### ISSUE THREAD

**Issue by bradyt** [exercism/request-new-language-track#68]
**What programming language should we add?**

Nix the expression language.

**What is the official website for the language?**

https://nixos.org/nix/manual/#ch-expression-language
https://nixos.wiki/wiki/Nix_Expression_Language

**Is this a language that comes in many variants? If so, which variant should we support?**

No.

**Does the language have an official logo?** If so

Yes.

- please include a link to an example
    - https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg
- please list the attribution rights of that logo
    - > The logo is made available under a CC-BY license.

      https://github.com/NixOS/nixos-artwork/tree/master/logo#license
      https://github.com/NixOS/nixos-artwork/tree/master/logo#credits

**Does the language have an unofficial logo?** If so

No.

- ~~please explain the ways in which people use the unofficial logo~~
- ~~please include a link to an example~~
- ~~please list the attribution rights of that logo~~

**Is there a testing framework available for the language?**

Yes. See https://nixos.org/nixos/manual/index.html#sec-nixos-tests.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** If so

Yes.

- what is Prism's canonical spelling for the language?
  - Nix
- what file extensions should be highlighted?
  - nix

**If it is not supported by Prism.js, what is the closest supported language it maps to?**

**Who will be leading the effort to launch the track?**

I don't know this yet. I was sort of going from section to section at https://github.com/exercism/request-new-language-track. This issue seemed a good place to start.

**Comment by kytrinyx** [comment]
Sweet! As soon as there is at least one person committed to launching the track, please report back here, and I will bootstrap a repository for you.

Thanks!

**Comment by bradyt** [comment]
I would like to try leading the effort to launching the track, or committing to launching the track.

**Comment by kytrinyx** [comment]
@bradyt Thank you ❤️ !

I've created a repository for you here:

https://github.com/exercism/nix/issues/1

Please submit individual pull requests with cohesive changes (e.g. documentation, CI setup, logo, individual exercises) to the new repo. I've given you commit access, so you can create branches right in the repo rather than creating a fork. Individual, smaller PRs will give us a few benefits:

* We can help catch things that should have been documented but weren't
* Ongoing development will be visible/transparent to others who are interested in following along
* It will be easier to go back in the git logs to figure things out

Welcome :heart: :heart: :heart:
