### ISSUE TITLE
Adding Z3 language

### ISSUE THREAD

**Issue by Newby555** [exercism/request-new-language-track#93]
**What programming language should we add?**
Z3

**What is the official website for the language?**
Z3 is relatively new and was started as an open-source language by Microsoft Research. Therefore, I believe this is similar to an "official website":  https://github.com/Z3Prover/z3

**Is this a language that comes in many variants? If so, which variant should we support?**
Z3 can be integrated with multiple higher-level languages. We will support Python integration.

**Does the language have an official logo?** 
No

**Does the language have an unofficial logo?** If so
- please explain the ways in which people use the unofficial logo
- please include a link to an example
- please list the attribution rights of that logo
A logo is utilized on the github page linked above as the "official website" and can be found here: https://www.google.com/search?q=z3+programming&tbm=isch&ved=2ahUKEwiA2cvRl-XuAhUPdqwKHayQAjIQ2-cCegQIABAA&oq=z3+programming&gs_lcp=CgNpbWcQAzIECCMQJzIECCMQJzIECAAQGDIECAAQGFC20QVYttIFYL_UBWgAcAB4AIABW4gBogGSAQEymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=5eQmYMDSLo_ssQWsoYqQAw&safe=active#imgrc=6mlmkJfK_-vl2M. I could not find attribution rights for this image.

**Is there a testing framework available for the language?**
There is a testing framework for Z3 when it is integrated with Python. It can use the SMT-LIB2 standard.

**Is this language listed as 'supported' by [Prism.js]([http://prismjs.com/#languages-list)?** 
No

**If it is not supported by Prism.js, what is the closest supported language it maps to?**
Python

**Who will be leading the effort to launch the track?**
I am part of a group of 5 that plans to add 10-15 exercises to this track over the next 2-3 months.

**Comment by iHiD** [comment]
@Newby555 Great. Thanks! :) We'll bootstrap a new track for you on Tuesday. 

So that you're aware, Exercism is currently in a weird 2-month window before v3 launching where everything is in flux, so I'll have to beg your patience as things will be a little less organised/clear than normal. You can still work on building the track but we might need to script some PRs for you to rearrange directory structures etc during the period, and you will find that the docs are somewhat in transition too. But please ask @ErikSchierboom any questions (opening issues is great, or on Slack too). If you're not on Slack yet, please email erik@exercism.io and he'll get you set up :)

**Comment by kytrinyx** [comment]
Your repo is ready for you here: https://github.com/exercism/z3/issues/1

✨ Thanks for taking the time to spin up a Z3 track!

**Comment by kytrinyx** [comment]
I've been looking at some of the language tracks that haven't gotten a lot of attention over the past few years, and this one is a bit of an odd one out.

Despite it being called a language, it's more often referred to as a "theorem prover". As such it really doesn't fit into the Exercism mold.

There was a flurry of activity in June and July 2021, and there are 14 exercises (including Hello World). All the other commits are from bots or Erik doing work to get tracks into shape for v3.

I get a 404 on exercism.org for the track, so it seems like it hasn't made it onto the site yet: https://exercism.org/tracks/z3

I wish I had done better due diligence before we created the repository for this, and I feel bad for coming back 18 months later to say that I don't think it makes a good candidate, but from what I can tell it is not a good fit for the platform since the intended scope that it applies to is so narrowly focused.

I would like to revert the decision to add the track, and archive the track repository.

@iHiD @ErikSchierboom what do you think?

**Comment by ErikSchierboom** [comment]
I agree with that fully.
